services:
  postgres:
    build:
      context: .
      args:
        - URL=${URL}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${HOST_PORT}:5432
